package:
  name: ramtools
  version: "0.0.0"

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script: python setup.py install --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  requires:
    - pytest
  imports:
    - pyfooty

about:
  home: https://github.com/rmatsum836/pyfooty
  license: MIT License
  summary: Python package to parse stats from FBRef
